[project]
name = "citadel"
version = "0.0.1"
description = "Stream, share and download your favourite music, videos all from one website."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.4",
    "quart>=0.19.8",
    "uvicorn>=0.32.0",
]
